name: Test Workflow

on:
  workflow_dispatch:
env:
  GITHUB_ACTOR: ${{ github.actor }}
jobs:
  print_properties:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "$GITHUB_TOKEN"
          env:
            GITHUB_TOKEN: ${{ secrets[format('TOKEN_{0}', $GITHUB_ACTOR)] }}
