name: Test Workflow

on:
  workflow_dispatch:
env:
  GITHUB_ACTOR: ${{ github.actor }}
jobs:
  print_properties:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets[format('TOKEN_{0}', env.GITHUB_ACTOR)] }}
        run: |
          echo "$GITHUB_TOKEN"
          
