name: Publish Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        GITHUB_ACTOR: ${{ github.actor }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run:  echo "$GITHUB_ACTOR"
